### ISSUE TITLE
レビュー1回目

### ISSUE THREAD

**Issue by yamaryo416** [worldwidepark/javascript-homework#1]

**Comment by yamaryo416** [comment]
- node_modulesは基本的にgithubに載せずgitignoreした方がいいですね。

- yearとmonthはnumberの方がいいですね。new Dateに渡す引数は、number型で、現状だとエラーは出ていないですが、typescriptだとエラーが出ると思います。
```
let year = today.getFullYear();
...
month = Number(program.opts().month);
...
month = today.getMonth() + 1
...

console.log(`       ${String(month).padStart(2, "0")}月 ${year}`);
```

- console.logをreturnしている感じなので、以下の方がいいですね。
```
else {
  console.log("入力値が正しくありません。");
  return;
}

```

- month, firstDayOfWeek, week以外は、定数（letではなく、const）で定義した方がいいかなと思いました。
```
処理中に値が変わるもの　let
処理中に値が変わらないもの　const
```

- firstDateOfWeekの変数名はstartDateOfSecondWeekの方がいいかなと思いました。

**Comment by yamaryo416** [comment]
綺麗にかけてますね！
timeZoneを意識していて素晴らしい。
LGTMです！

**Comment by worldwidepark** [comment]
ありがとうございます。
ご指摘いただいた項目を確認し、修正しました。
